name: Testing applications sources

on:
  push:
    paths:
      - '*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Linting on Python ${{ matrix.python-version }}

    steps:
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: SG60/setup-poetry@v1
        run: poetry install --with dev
      - name: Check code style (using flake8)
        run: flake8 crasher
      - name: Check correct typing (using mypy)
        run: mypy crasher
  #unittest:
  # TODO: Add unittests to this workflow